version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

clone_depth: 1

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

before_build:
  - nuget restore

build:
  parallel: true
  project: duilib_tutorial.sln
  verbosity: minimal

