version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2019

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release
  
build:
  parallel: true
  project: duilib_tutorial/duilib_tutorial.sln
  verbosity: minimal